### ISSUE TITLE
Introduction to databases and SQL - July 2, 2017 @ 6-7pm, NMB 207

### ISSUE THREAD

**Issue by pipitone** [queenscoders/Events#2]
Databases are useful when you have lots of related tabular data (think excel spreadsheets), and you need to merge, filter, or general extract pieces of your data for further analysis. I'll introduce you to the basics of databases and SQL -- the language for interacting with a database. After a quick tour, we can talk about how you might (or might not) want to use a database to manage your study data.  We will be roughly following the [Data Carpentry database lessons](http://www.datacarpentry.org/sql-ecology-lesson/).

**You'll need:** 

- **Where**: Rm 207 in NMB ([New Medical Building](http://www.openstreetmap.org/way/50501629))
- **When**: July 2, 2017. 6-7pm
- **Instructor**: @pipitone
- **What to bring**: Laptop + Firefox and the [SQLite Manager plugin](https://addons.mozilla.org/en-US/firefox/addon/sqlite-manager/)

**Comment by boobydylan** [comment]
Yes! I will be there! 

Jon, how do I catch up? Make out session?

Yours,
BoobyDylan

**Comment by liannev** [comment]
I'll be there too.

**Comment by pipitone** [comment]
We covered essentially parts 1-3 of the Data Carpentry lesson.
